Repository zowe/docs-site, pull requests merged in 2018-10, with the labels that each got.

#104 Issue #103: add pipeline
  Jenkinsfile
  package.json
Labels: review

#107 Fixed build errors by fixing toc
  docs/.vuepress/config.js
  yarn.lock
Labels: review

#101 Docs staging
  docs/.vuepress/config.js
  docs/.vuepress/public/Zowe_User_Guide.pdf
  docs/.vuepress/public/Zowe_User_Guide_0.9.0.pdf
  docs/.vuepress/public/sitemap.xml
  docs/README.md
  docs/guides/api-mediation-onboard-a-sprint-boot-rest-api-service.md
  docs/guides/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/guides/api-mediation-usingapiml.md
  docs/guides/zlux-tutorials.md
  docs/images/api-mediation/cntrlr-detail.png
  docs/images/api-mediation/expanded.png
  docs/images/api-mediation/green-check.jpg
  docs/images/api-mediation/newheader.png
  docs/images/api-mediation/newswagger.png
  docs/images/api-mediation/service-detail-info.png
  docs/images/api-mediation/x-graphic.jpg
  docs/user-guide/Zowe_User_Guide.ditamap
  docs/user-guide/api-mediation-api-catalog.md
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-extending.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-installplugins.md
  docs/user-guide/install-zos.md
  docs/user-guide/mvd-logutility.md
  docs/user-guide/mvd-uribroker.md
  docs/user-guide/mvd-using.md
  docs/user-guide/overview.md
  docs/user-guide/summaryofchanges.md
Labels: review

#108 Rocket doc
  docs/user-guide/mvd-using.md
Labels: review

#110 correct typo
  docs/user-guide/cli-cicsplugin.md
Labels: review

#111 Docs staging
  docs/.vuepress/config.js
  docs/user-guide/cli-installplugins.md
Labels: review

#114 Docs staging
  docs/guides/api-mediation-onboard-a-sprint-boot-rest-api-service.md
Labels: review

#115 add PDF
  docs/.vuepress/public/Zowe_User_Guide_0.9.1.pdf
Labels: review

#116 Automatically Publish
  Jenkinsfile
Labels: review

#113 Test links on windows
  Jenkinsfile
  package-lock.json
  package.json
  yarn.lock
Labels: review

#117 only allow publishing from master branch
  Jenkinsfile
Labels: review

#119 issue #118 registry.yarnpkg.com is not stable
  Jenkinsfile
  package-lock.json
  package.json
  yarn.lock
Labels: review

#120 SOC/release notes update
  docs/user-guide/mvd-using.md
  docs/user-guide/summaryofchanges.md
Labels: review

#121 Declutter API onboarding TOC
  docs/.vuepress/config.js
Labels: Docs, review

#102 Add instructions how to define static API to the Zowe runtime
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: review

#125 Cli keytar removal update
  docs/user-guide/cli-installcli.md
  docs/user-guide/systemrequirements.md
Labels: review

#126 Introduce developer tutorials for Zowe CLI
  docs/.vuepress/config.js
  docs/guides/cli-devTutorials.md
  docs/guides/cli-developPlugins.md
  docs/guides/cli-developing-a-plugin.md
  docs/guides/cli-extending-a-plugin.md
  docs/guides/cli-implement-profiles.md
  docs/guides/cli-installing-sample-plugin.md
  docs/guides/cli-setting-up.md
  docs/images/guides/CLI/InstalledSample.png
  docs/images/guides/CLI/SampleOutput.png
  docs/images/guides/CLI/completedSample.png
  docs/images/guides/CLI/diffOutput.png
  docs/images/guides/CLI/htmlDiff.png
  docs/images/guides/CLI/pipeOutput.png
  docs/user-guide/cli-installcli.md
  docs/user-guide/systemrequirements.md
  package-lock.json
Labels: Docs, review

#127 Cli dev staging
  docs/guides/cli-devTutorials.md
Labels: review

#123 Update 0.9.0 PDF
  docs/.vuepress/public/Zowe_User_Guide_0.9.0.pdf
Labels: review

#124 Update gettingstarted.md
  docs/user-guide/gettingstarted.md
Labels: review

#132 Update PDF
  docs/.vuepress/public/Zowe_User_Guide_0.9.1.pdf
Labels: Docs, review

#134 Upload a build file to test doc build
  buildsmu.dcsbuild
Labels: review

#135 Minor fix
  docs/guides/cli-extending-a-plugin.md
  docs/user-guide/systemrequirements.md
Labels: Docs, review

#136 Update buildsmu.dcsbuild
  buildsmu.dcsbuild
Labels: review

#128 Split the API overview to new topic and describe steps for identification
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
  docs/user-guide/api-mediation/api-mediation-onboard-overview.md
  docs/user-guide/api-mediation/api-mediation-overview.md
  docs/user-guide/api-mediation/diagrams/rest-api-components-sample.plantuml
  docs/user-guide/api-mediation/diagrams/rest-api-components-sample.svg
Labels: review

#138 Api mediation doc
  .gitignore
  docs/.vuepress/public/sitemap.xml
  docs/user-guide/api-mediation/api-mediation-api-catalog.md
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-java-rest-api-service.md
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-spring-boot-rest-api-service.md
  docs/user-guide/api-mediation/api-mediation-onboard-overview.md
  docs/user-guide/api-mediation/api-mediation-overview.md
  docs/user-guide/api-mediation/diagrams/API-Catalog-Tile.png
  docs/user-guide/api-mediation/diagrams/Expanded-Catalog-Tile.png
  docs/user-guide/api-mediation/diagrams/Service-Status.png
  docs/user-guide/api-mediation/diagrams/Service-detail.png
  docs/user-guide/api-mediation/diagrams/cntrlr-detail.PNG
  docs/user-guide/api-mediation/diagrams/endpoint-detail.PNG
  docs/user-guide/api-mediation/diagrams/green-check.jpg
  docs/user-guide/api-mediation/diagrams/image2018-2-26 14_53_46.png
  docs/user-guide/api-mediation/diagrams/rest-api-components-sample.plantuml
  docs/user-guide/api-mediation/diagrams/rest-api-components-sample.svg
  docs/user-guide/api-mediation/diagrams/rest-api-components.plantuml
  docs/user-guide/api-mediation/diagrams/rest-api-components.svg
  docs/user-guide/api-mediation/diagrams/service-detail-info.PNG
  docs/user-guide/api-mediation/diagrams/x-graphic.jpg
Labels: Docs, review

#139 Api onboarding intro
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: Docs, review

#142 remove extraneous files
  docs/user-guide/api-mediation/api-mediation-onboard-an-existing-java-rest-api-service.md
Labels: review

#143 Api cleanup
  docs/.vuepress/config.js
  docs/guides/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
  docs/user-guide/api-mediation/api-mediation-onboard-overview.md
Labels: review

#146 Fix grammar in line 284.
  docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: review

#147 Fix grammar in line 286.
  docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: apiml, review

#151 Fix prereq
  docs/user-guide/cli-configuringcli.md
  docs/user-guide/systemrequirements.md
Labels: doc site, docs

#152 Correct the explorer JES URL
  docs/user-guide/summaryofchanges.md
Labels: review

#156 revert anchor test
  docs/user-guide/cli-installcli.md
Labels: review

#162 Name changes for Atlas API before API Mediation
  docs/user-guide/install-zos.md
  docs/user-guide/troubleshootinstall.md
  docs/user-guide/usingapis.md
Labels: review

#163 Changed the CSRF section
  docs/user-guide/troubleshootinstall.md
Labels: review

#160 Vs code plugin
  docs/.vuepress/config.js
  docs/user-guide/Zowe_User_Guide.ditamap
  docs/user-guide/cli-extending.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-vscodeplugin.md
  docs/user-guide/overview.md
  docs/user-guide/summaryofchanges.md
  docs/user-guide/systemrequirements.md
Labels: review

#170 fix prereqs
  docs/user-guide/cli-cicsplugin.md
Labels: review

#172 Fix a link
  docs/user-guide/cli-installcli.md
Labels: review

#164 Refactor article title
  docs/guides/api-mediation-onboard-a-sprint-boot-rest-api-service.md
Labels: docs, review

#165 Refactor article title
  docs/guides/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Labels: docs, review

#168 Refactor article title
  docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: docs, review

#166 Refactor article title
  docs/guides/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
Labels: docs, review

#176 Typo AXE->AXR
  docs/user-guide/systemrequirements.md
Labels: review

#175 Refactor Externalize Parameters
  docs/guides/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Labels: docs, review

#177 Fix a display issue
  docs/user-guide/troubleshootinstall.md
Labels: review

#182 Cics package
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-installcli.md
Labels: review

#161 Merge docs-staging branch to master
  docs/README.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/install-zos.md
  docs/user-guide/summaryofchanges.md
  docs/user-guide/systemrequirements.md
Labels: docs, review

#180 Updated requirement for node.js
  docs/user-guide/summaryofchanges.md
  docs/user-guide/systemrequirements.md
Labels: review

#186 0.9.2 PDF file
  docs/.vuepress/public/Zowe_User_Guide_0.9.2.pdf
  docs/user-guide/cli-vscodeplugin.md
  docs/user-guide/summaryofchanges.md
  docs/user-guide/systemrequirements.md
Labels: review

#185 Add read-only credential values for Zowe Artifactory.
  docs/guides/api-mediation-onboard-a-sprint-boot-rest-api-service.md
  docs/user-guide/summaryofchanges.md
Labels: docs, review

#191 fix a link issue
  docs/user-guide/cli-installcli.md
Labels: review

#193 Add links to the bug fixes
  docs/user-guide/summaryofchanges.md
Labels: review

#196 Refactor Onboarding REST API without code changes.
  docs/guides/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
  docs/user-guide/api-mediation/api-mediation-onboard-overview.md
  docs/user-guide/api-mediation/diagrams/rest-api-components.plantuml
  docs/user-guide/api-mediation/diagrams/rest-api-components.svg
Labels: docs, review

#199 Review DB2 Plugin Install
  docs/user-guide/cli-db2plugin.md
Labels: review
