Repository zowe/docs-site, pull requests merged in 2019-04, with the labels that each got.

#450 Added note for ZWES.IS
  docs/troubleshoot/troubleshoot-app-framework.md
Labels: review

#451 Add Zowe CLI enhancements since Zowe 1.0.1
  docs/getting-started/summaryofchanges.md
Labels: review

#448 #446 Remove the z/OS prereq npm from system requirements
  docs/user-guide/systemrequirements.md
Labels: docs, review

#455 Update mvd-creatingappplugins.md
  docs/extend/extend-desktop/mvd-creatingappplugins.md
Labels: review

#456 Janan07 keystore patch 1
  docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
Labels: apiml, docs, review

#449 1.1.0 documentation
  docs/.vuepress/config.js
  docs/.vuepress/public/zosmf_lite_samples.zip
  docs/.vuepress/versions.json
  docs/README.md
  docs/api-mediation/api-mediation-overview.md
  docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
  docs/extend/extend-apiml/api-mediation-onboard-overview.md
  docs/extend/extend-apiml/api-mediation-security.md
  docs/getting-started/diagrams/service-relationship-diagram.png
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
  docs/images/common/zowe-install-location.png
  docs/images/zosmf/IZUG349I.png
  docs/images/zosmf/IZUMKFS1.png
  docs/images/zosmf/IZUMKFS2.png
  docs/images/zosmf/IZUMKFS3.png
  docs/images/zosmf/Welcome.png
  docs/troubleshoot/troubleshoot-app-framework.md
  docs/user-guide/api-mediation-api-catalog.md
  docs/user-guide/api-mediation/api-mediation-api-catalog.md
  docs/user-guide/api-mediation/api-mediation-overview.md
  docs/user-guide/api-mediation/diagrams/service-relationship-diagram.png
  docs/user-guide/cli-configuringcli.md
  docs/user-guide/install-nodejs-zos.md
  docs/user-guide/install-zos.md
  docs/user-guide/installandconfig.md
  docs/user-guide/mvd-using.md
  docs/user-guide/systemrequirements-zosmf-lite.md
  docs/user-guide/systemrequirements-zosmf.md
  docs/user-guide/systemrequirements.md
  package.json
Labels: docs, review

#457 Fix typo
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: docs, review

#459 Fix link issues.
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: review

#458 Fix a format issue
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: review

#460 [v1.0.x] Backport sysreq doc fixes to v1.0.x
  docs/.vuepress/config.js
  docs/README.md
  docs/images/common/zowe-install-location.png
  docs/troubleshoot/troubleshoot-app-framework.md
  docs/user-guide/install-nodejs-zos.md
  docs/user-guide/installandconfig.md
  docs/user-guide/systemrequirements-zosmf.md
  docs/user-guide/systemrequirements.md
Labels: docs, review

#461 Docs staging
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: apiml, docs, review

#463 Remove API ML Release notes
  docs/getting-started/summaryofchanges.md
Labels: apiml, docs, review

#466 fix link issues
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: review

#471 Add Feedback link to doc site
  docs/.vuepress/config.js
  docs/.vuepress/theme/styles/config.styl
Labels: review

#473 Update CLIReference_Zowe.pdf
  docs/.vuepress/public/CLIReference_Zowe.pdf
Labels: review

#465 Clean up Overview
  docs/.vuepress/style.styl
  docs/getting-started/overview.md
Labels: docs, review

#481 Merge updating cli
  docs/.vuepress/config.js
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-updatingcli.md
Labels: review

#480 clarify prereqs not for CLI
  docs/user-guide/systemrequirements.md
Labels: docs, review

#489 Desktop customization switch language
  docs/user-guide/mvd-using.md
Labels: review

#488 Backport system requirement fixes to v1.0.x doc
  docs/user-guide/systemrequirements.md
Labels: review

#490 Embed hotjar code to create a heat map
  docs/.vuepress/config.js
Labels: docs, review

#491 Update config.js
  docs/.vuepress/config.js
Labels: review

#477 Update artifact version and add yml sample for dev mode
  docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
Labels: review

#493 typo
  docs/getting-started/summaryofchanges.md
Labels: review

#492 Installer 1.1.1 changes
  docs/getting-started/summaryofchanges.md
Labels: review

#494 Update overview pdf
  docs/README.md
Labels: review

#497 Extending rbac
  docs/extend/extend-desktop/mvd-dataservices.md
  docs/user-guide/mvd-configuration.md
Labels: docs, review

#440 Added zos-uss command
  docs/user-guide/cli-usingcli.md
Labels: cli, docs, review

#495 Added language on new gzip and brotli compressed file support.
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
Labels: docs, review
