Repository zowe/docs-site, pull requests merged in 2019-02, with the labels that each got.

#351 fix an issue on archiving; clean pdf tmp folder
  Jenkinsfile
  docs/.pdf/build.sh
Labels: review

#348 Update the Node.js version
  docs/user-guide/systemrequirements.md
Labels: review

#356 stop start updated
  docs/user-guide/install-zos.md
  docs/user-guide/install-zss-md
Labels: review

#357 Added ICSF changes
  docs/user-guide/install-zos.md
Labels: review

#353 Refactor article formatting
  docs/extend/extend-apiml/api-mediation-security.md
Labels: docs, review

#359 Update install-zos.md
  docs/user-guide/install-zos.md
Labels: review

#360 Fix Command
  docs/user-guide/install-zos.md
Labels: review

#364 WIP - draft of tss/acf2 commands for ZSS
  docs/user-guide/install-zos.md
Labels: review

#362 Fix springv1 guidelines
  docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
Labels: review

#338 Doc changes for 1.0.0
  docs/.pdf/Zowe_Documentation.ditamap.template
  docs/.vuepress/config.js
  docs/.vuepress/public/sitemap.xml
  docs/README.md
  docs/api-mediation/api-mediation-overview.md
  docs/appendix/bill-of-materials.md
  docs/appendix/tpsr.md
  docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/extend/extend-apiml/api-mediation-security.md
  docs/extend/extend-cli/cli-devTutorials.md
  docs/extend/extend-cli/cli-implement-profiles.md
  docs/extend/extend-desktop/mvd-apptoappcommunication.md
  docs/extend/extend-desktop/zlux-app-server.md
  docs/extend/extend-desktop/zlux-workshop-user-browser.md
  docs/extend/extender-architecture.md
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
  docs/getting-started/zowe-architecture.md
  docs/images/api-mediation/apiml-components.plantuml
  docs/images/api-mediation/apiml-components.svg
  docs/images/common/zowe-architecture.png
  docs/images/common/zowe-architecture.pptx
  docs/images/common/zowe-install-location.png
  docs/images/common/zowe-install-location.pptx
  docs/images/mvd/mvd_workflow1.png
  docs/images/mvd/mvd_workflow2.png
  docs/images/mvd/mvd_workflow3.png
  docs/troubleshoot/troubleshootinstall.md
  docs/user-guide/Zowe_User_Guide.ditamap
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-configuringcli.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-extending.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-installplugins.md
  docs/user-guide/cli-usingcli.md
  docs/user-guide/cli-vscodeplugin.md
  docs/user-guide/install-zos.md
  docs/user-guide/installandconfig.md
  docs/user-guide/installroadmap.md
  docs/user-guide/mvd-configuration.md
  docs/user-guide/mvd-using.md
  docs/user-guide/systemrequirements.md
  docs/user-guide/uninstall.md
  docs/user-guide/unused-files/troubleshootinstall.md
  docs/user-guide/unused-files/usingapis.md
  docs/user-guide/usingapis.md
  package-lock.json
  package.json
Labels: review

#368 proper link to latest pdf
  docs/README.md
Labels: review

#369 minor fixes to zss security
  docs/user-guide/install-zos.md
Labels: review

#370 Fix typos
  docs/.vuepress/config.js
  docs/user-guide/install-zos.md
Labels: review

#371 Update the link to 0.9.5 PDF file and update the homepage
  docs/.vuepress/config.js
  docs/.vuepress/public/Zowe_User_Guide_0.9.5.pdf
  docs/README.md
Labels: review

#373 Update the Zowe architecture to remove JMON
  docs/images/common/zowe-architecture.png
  docs/images/common/zowe-architecture.pptx
Labels: review

#377 #376 Update the location of the prereq check info
  docs/user-guide/install-zos.md
Labels: review

#378 removed the word beta
  docs/README.md
Labels: review

#382 show version dropdown for 0.9.x doc
  docs/.vuepress/versions.json
Labels: review

#386 Fixed typo in PDF title
  docs/.pdf/Zowe_Documentation.ditamap.template
Labels: review

#387 Fix wrong termination command for the cross-memory server
  docs/user-guide/install-zos.md
Labels: review

#389 Change ZISSRV01 to ZWESIS01 in the architecture diagram
  docs/images/common/zowe-architecture.png
  docs/images/common/zowe-architecture.pptx
Labels: review

#392 Update how to view the ZWES.IS users
  docs/user-guide/install-zos.md
Labels: review

#390 update docs-staging from master
  docs/.pdf/Zowe_Documentation.ditamap.template
  docs/images/common/zowe-architecture.png
  docs/images/common/zowe-architecture.pptx
  docs/user-guide/install-zos.md
Labels: review

#395 Fix typo
  docs/getting-started/cli-getting-started.md
Labels: review

#396 do some fixes to change size of the file
  docs/user-guide/systemrequirements.md
Labels: review

#398 Docs staging
  .gitignore
  README.md
  docs/.pdf/README.md
  docs/.pdf/Zowe_Documentation.ditamap.template
  docs/.vuepress/config.js
  docs/.vuepress/public/Zowe_Documentation_1.0.0.pdf
  docs/README.md
  docs/getting-started/summaryofchanges.md
  docs/images/common/zowe-architecture.png
  docs/images/common/zowe-architecture.pptx
  docs/user-guide/Zowe_User_Guide.ditamap
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-installplugins.md
  docs/user-guide/gettingstarted.md
  docs/user-guide/install-zos.md
  docs/user-guide/unused-files/cli-enabledisablexperimentalcommands.md
  docs/user-guide/unused-files/mvd-appfilesystem.md
  docs/user-guide/unused-files/mvd-configterminalappports.md
  docs/user-guide/unused-files/mvd-verifysystemswreqs.md
  docs/user-guide/unused-files/troubleshootinstall.md
  docs/user-guide/unused-files/usingapis.md
  faq.md
  yarn.lock
Labels: review

#394 Create CLI Quick Start Guide
  docs/.vuepress/config.js
  docs/getting-started/cli-getting-started.md
Labels: cli, docs, review
