Repository zowe/docs-site, pull requests merged in 2019-05, with the labels that each got.

#504 v1.2.0 documentation
  Jenkinsfile
  README.md
  docs/.vuepress/config.js
  docs/.vuepress/public/Zowe_Documentation_1.1.0.pdf
  docs/.vuepress/versions.json
  docs/README.md
  docs/appendix/tpsr.md
  docs/extend/extend-api/ReactJSUI.md
  docs/extend/extend-api/existingAPI.md
  docs/extend/extend-api/libertyAPI.md
  docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/extend/extend-desktop/mvd-dataservices.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/getting-started/freqaskques.md
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
  docs/troubleshoot/troubleshoot-app-framework.md
  docs/troubleshoot/troubleshoot-cli.md
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-configuringcli.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-extending.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-installplugins.md
  docs/user-guide/cli-usingcli.md
  docs/user-guide/cli-vscodeplugin.md
  docs/user-guide/install-nodejs-zos.md
  docs/user-guide/install-zos.md
  docs/user-guide/mvd-configuration.md
  docs/user-guide/mvd-using.md
  docs/user-guide/systemrequirements-zosmf-lite.md
  docs/user-guide/systemrequirements-zosmf.md
  docs/user-guide/uninstall.md
Labels: review

#505 update description to 1.2.x
  docs/.vuepress/config.js
Labels: review

#510 fix incorrect syntax for cics and db2 validate command
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
Labels: cli, docs, review

#513 Add ciphers configuration
  docs/extend/extend-apiml/api-mediation-security.md
Labels: apiml, docs, review

#516 Java enabler fixes
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
Labels: review

#518 Add gif to Displaying Zowe CLI Help
  docs/images/guides/CLI/GetHelp.gif
  docs/user-guide/cli-usingcli.md
  package-lock.json
Labels: cli, docs, review

#519 Added SW Reg for CLI Plugins
  docs/.vuepress/config.js
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-swreqplugins.md
  package-lock.json
Labels: review

#520 An example for Create a Zowe CLI profile (issue #192)
  docs/user-guide/cli-configuringcli.md
Labels: review

#524 Update the cp command to match the install script
  docs/user-guide/install-zos.md
Labels: review

#525 Java enablers doc update
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/user-guide/install-zos.md
Labels: apiml, docs, review

#523 issue #434 copy to clipboard
  docs/.vuepress/config.js
  docs/.vuepress/theme/Page.vue
  docs/.vuepress/theme/styles/clipboard.styl
  docs/.vuepress/theme/styles/code.styl
  docs/.vuepress/theme/styles/theme.styl
  docs/.vuepress/theme/styles/tooltip.styl
Labels: review

#521 replaced all instances of Prerequisites with Software Requirements
  docs/getting-started/overview.md
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-installplugins.md
  docs/user-guide/cli-swreqplugins.md
  docs/user-guide/cli-vscodeplugin.md
Labels: review

#527 Button for CLI Ref download
  docs/README.md
Labels: docs, review

#437 Add TSS / ACF2 manual commands for BPX
  docs/user-guide/install-zos.md
Labels: review

#469 Move UI guidelines to the doc site
  docs/.vuepress/config.js
  docs/contribute/contributing.md
  docs/contribute/guidelines-ui/appicon.md
  docs/contribute/guidelines-ui/colors.md
  docs/contribute/guidelines-ui/grid.md
  docs/contribute/guidelines-ui/icon.md
  docs/contribute/guidelines-ui/typography.md
  docs/contribute/guidelines-ui/ui.md
  docs/images/extender/dark_palette.png
  docs/images/extender/full_palette.png
  docs/images/extender/grid_desktop-1024x780.png
  docs/images/extender/grid_mobile-1024x709.png
  docs/images/extender/icon_sample1.png
  docs/images/extender/icon_sample2-1024x283.png
  docs/images/extender/icon_sample3.png
  docs/images/extender/icon_sample4.png
  docs/images/extender/icon_sample5.png
  docs/images/extender/icons_sample-1024x753.png
  docs/images/extender/light_palette.png
  docs/images/extender/type_bold_sample.png
  docs/images/extender/type_light_sample.png
  docs/images/extender/type_regular_sample.png
  docs/images/extender/type_sample.png
  docs/images/extender/type_scale_desktop-1024x533.png
  docs/images/extender/type_scale_mobile-1024x461.png
Labels: docs, review

#529 issue #475 style details/summary button
  docs/.vuepress/theme/Page.vue
  docs/.vuepress/theme/styles/clipboard.styl
  docs/.vuepress/theme/styles/code.styl
  docs/.vuepress/theme/styles/details.styl
  docs/.vuepress/theme/styles/theme.styl
  docs/.vuepress/theme/styles/tooltip.styl
Labels: review

#530 issue #344 add section context on top of toc
  docs/.vuepress/config.js
  docs/.vuepress/theme/Sidebar.vue
  docs/.vuepress/theme/styles/theme.styl
  docs/.vuepress/theme/util.js
Labels: review

#534 Fix job name error
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: review

#503 Node server to node cluster
  docs/extend/extend-desktop/mvd-creatingappplugins.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/extend/extend-desktop/zlux-app-server.md
  docs/extend/extend-desktop/zlux-workshop-user-browser.md
Labels: review

#531 issue #498 perform link check only on current build
  Jenkinsfile
  package-lock.json
  package.json
Labels: review

#541 compare change across these branches
  Jenkinsfile
  docs/.vuepress/config.js
  docs/.vuepress/theme/Page.vue
  docs/.vuepress/theme/Sidebar.vue
  docs/.vuepress/theme/styles/clipboard.styl
  docs/.vuepress/theme/styles/code.styl
  docs/.vuepress/theme/styles/details.styl
  docs/.vuepress/theme/styles/theme.styl
  docs/.vuepress/theme/styles/tooltip.styl
  docs/.vuepress/theme/util.js
  docs/extend/extend-desktop/mvd-creatingappplugins.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/extend/extend-desktop/zlux-app-server.md
  docs/extend/extend-desktop/zlux-workshop-user-browser.md
  docs/user-guide/systemrequirements-zosmf-lite.md
  package-lock.json
  package.json
Labels: review

#540 Replace placeholder credentials for maven guide with real ones
  docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Labels: review

#542 Replace placeholder credentials for maven guide with real ones
  docs/extend/extend-apiml/api-mediation-onboard-a-spring-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/user-guide/install-zos.md
Labels: review

#545 Fix link
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/extend/extend-desktop/mvd-dataservices.md
  docs/extend/extend-desktop/zlux-app-server.md
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-usingcli.md
  docs/user-guide/cli-vscodeplugin.md
  docs/user-guide/install-zos.md
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: review

#539 Update release notes
  docs/getting-started/summaryofchanges.md
Labels: docs, review

#548 Fix remaining links
  docs/extend/extend-apiml/api-mediation-security.md
  docs/extend/extend-desktop/zlux-app-server.md
  docs/user-guide/cli-configuringcli.md
  docs/user-guide/cli-usingcli.md
  docs/user-guide/mvd-configuration.md
  docs/user-guide/systemrequirements-zosmf-lite.md
Labels: review

#552 Changed to enable debug mode introduction
  docs/troubleshoot/troubleshoot-apiml.md
Labels: docs, review

#547 Create John-A-Davies-docs-site.txt
  dco_signoffs/John-A-Davies-docs-site.txt
Labels: review

#546 Create John Davies-docs-site.txt
  dco_signoffs/John Davies-docs-site.txt
Labels: review

#553 Move code guidelines to docs-site
  docs/.vuepress/config.js
  docs/contribute/guidelines-code/categories.md
  docs/contribute/guidelines-code/code-and-patches.md
  docs/contribute/guidelines-code/documentation.md
  docs/contribute/guidelines-code/general.md
  docs/contribute/guidelines-ui/appicon.md
  package-lock.json
Labels: docs
