Repository zowe/docs-site, pull requests merged in 2019-01, with the labels that each got.

#310 Update TPSR libraries
  docs/getting-started/overview.md
Labels: apiml

#311 updated old references of RocketMVD
  docs/extend/extend-desktop/iframe-sample.md
  docs/extend/extend-desktop/mvd-desktopandwindowmgt.md
  docs/extend/extend-desktop/mvd-mvdandwindowmgt.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/extend/extend-desktop/mvd-uribroker.md
  docs/extend/extend-desktop/ui-intro.md
  docs/extend/extend-desktop/zlux-workshop-user-browser.md
Labels: review

#313 Doc-site names for issue 214
  docs/extend/extend-desktop/angular-sample.md
  docs/extend/extend-desktop/iframe-sample.md
  docs/extend/extend-desktop/mvd-apptoappcommunication.md
  docs/extend/extend-desktop/mvd-configdataservice.md
  docs/extend/extend-desktop/mvd-dataservices.md
  docs/extend/extend-desktop/mvd-logutility.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/extend/extend-desktop/mvd-uribroker.md
  docs/extend/extend-desktop/react-sample.md
  docs/extend/extend-desktop/ui-intro.md
  docs/extend/extend-desktop/zlux-example-server.md
  docs/extend/extend-desktop/zlux-tutorials.md
  docs/extend/extend-desktop/zlux-workshop-starter-app.md
Labels: review

#315 Fixed some wording and typos
  docs/extend/extend-desktop/iframe-sample.md
  docs/extend/extend-desktop/mvd-apptoappcommunication.md
  docs/extend/extend-desktop/mvd-configdataservice.md
  docs/extend/extend-desktop/react-sample.md
  docs/extend/extend-desktop/zlux-example-server.md
  docs/extend/extend-desktop/zlux-workshop-user-browser.md
Labels: review

#316 Security commands to read z/OSMF keyring
  docs/extend/extend-apiml/api-mediation-security.md
Labels: review

#296 0.9.5 docs
  docs/.vuepress/public/Zowe_User_Guide_0.9.5.pdf
  docs/README.md
  docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/extend/extend-apiml/api-mediation-security.md
  docs/getting-started/freqaskques.md
  docs/getting-started/summaryofchanges.md
  docs/troubleshoot/troubleshootinstall.md
  docs/user-guide/Zowe_User_Guide.ditamap
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/gettingstarted.md
  docs/user-guide/install-zos.md
  docs/user-guide/installandconfig.md
  docs/user-guide/installroadmap.md
  docs/user-guide/systemrequirements.md
  docs/user-guide/unused-files/troubleshootinstall.md
Labels: review

#320 Update the version, fix two naming issues
  docs/.vuepress/config.js
  docs/.vuepress/public/CA_Brightside_TPSRs.zip
  docs/.vuepress/public/zowe_apiml_tpsrs.zip
  docs/.vuepress/public/zowe_cli_tpsrs.zip
  docs/contributing.md
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
Labels: review

#319 update doc for jersey
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Labels: review

#324 Update config.js
  docs/.vuepress/config.js
Labels: review

#325 Fix broken code blocks and remove outdated diagram
  docs/extend/extend-apiml/api-mediation-security.md
Labels: apiml, review

#326 Added information about using the Editor
  docs/user-guide/mvd-using.md
Labels: review

#330 Update libertyAPI.md
  docs/extend/extend-api/libertyAPI.md
Labels: review

#333 Embed a related video in the docs
  docs/user-guide/cli-vscodeplugin.md
Labels: review

#335 Fix a display issue
  docs/extend/extend-apiml/api-mediation-onboard-overview.md
Labels: review

#336 Fix code display issues
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-rest-api-service-without-code-changes.md
Labels: review

#327 Remove Liberty references
  docs/.vuepress/config.js
  docs/.vuepress/public/sitemap.xml
  docs/README.md
  docs/extend/extend-apiml/api-mediation-security.md
  docs/extend/extender-architecture.md
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
  docs/images/api-mediation/apiml-components.svg
  docs/images/common/zowe-install-location.png
  docs/images/common/zowe-install-location.pptx
  docs/troubleshoot/troubleshootinstall.md
  docs/user-guide/Zowe_User_Guide.ditamap
  docs/user-guide/cli-installcli.md
  docs/user-guide/install-zos.md
  docs/user-guide/installandconfig.md
  docs/user-guide/installroadmap.md
  docs/user-guide/uninstall.md
  docs/user-guide/unused-files/troubleshootinstall.md
  docs/user-guide/usingapis.md
Labels: review

#337 Add a missing topic to TOC
  docs/.vuepress/config.js
  docs/extend/extend-apiml/api-mediation-security.md
Labels: review

#339 Change reference name of jersey enabler
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
Labels: review

#331 Security permissions needed for import of the z/OSMF certificates
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-jersey-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-security.md
  docs/user-guide/install-zos.md
Labels: review

#328 Document the use of .zowe_profile
  docs/user-guide/install-zos.md
Labels: review

#342 use new agent label
  Jenkinsfile
Labels: review

#341 use new agent label
  Jenkinsfile
Labels: review

#345 Versioning cli changes
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-installcli.md
  docs/user-guide/cli-installplugins.md
Labels: cli, review

#343 Incorporate comments
  docs/user-guide/install-zos.md
Labels: review

#321 Strip off Ca, Mfaas, eureka references
  docs/extend/extend-apiml/api-mediation-onboard-a-sprint-boot-rest-api-service.md
  docs/extend/extend-apiml/api-mediation-onboard-an-existing-java-rest-api-service-without-spring-boot-with-zowe-api-mediation-layer.md
  docs/extend/extend-apiml/api-mediation-security.md
Labels: review

#347 Edits while following the tutorial
  docs/extend/extend-desktop/zlux-app-server.md
Labels: review
