Repository zowe/docs-site, pull requests merged in 2020-07, with the labels that each got.

#1293 prefer IP address option for enablers
  docs/extend/extend-apiml/onboard-plain-java-enabler.md
Labels: apiml

#1290 release notes for 1.13
  docs/getting-started/summaryofchanges.md
Labels: web ui

#1296 Add CLI release notes 1.13.0
  dco_signoffs/Brandon Jenkins-docs-site.txt
  docs/appendix/tpsr.md
  docs/getting-started/summaryofchanges.md
Labels: cli, docs

#1303 Zowe Explorer release notes for Zowe (1.13) update
  docs/getting-started/summaryofchanges.md
Labels: area: zowe-explorer, docs

#1316 Fix an incorrect task name
  docs/user-guide/configure-xmem-server.md
Labels: area: zos-install, type: bug

#1309 Changes to "Updating CLI" procedure
  docs/user-guide/cli-updatingcli.md
Labels: area: cli, docs

#1315 Add instructions for configuring connection-timeout on files and jobs apis
  docs/.vuepress/pages.json
  docs/user-guide/configure-data-sets-jobs-api.md
Labels: area: misc, type: enhancement

#1214 Keyring support documentation
  docs/user-guide/configure-certificates.md
Labels: area: zos-install, type: enhancement

#1318 User/joewinchester/x mem updates
  docs/user-guide/configure-xmem-server.md
Labels: area: zos-install, type: enhancement
