Repository zowe/docs-site, pull requests merged in 2021-02, with the labels that each got.

#1557 Client cert auth add zosmf rights prerequisite
  docs/extend/extend-apiml/api-mediation-security.md
Labels: x509

#1520 API ML - Obtaining Information about API Services
  docs/.vuepress/pages.json
  docs/extend/extend-apiml/service-information.md
  docs/user-guide/api-mediation/api-mediation-internal-configuration.md
Labels: docs

#1578 Clarify docs site readme build and preview instructions
  README.md
Labels: status: review
