Repository zowe/docs-site, pull requests merged in 2021-07, with the labels that each got.

#1697 Fix must gather
  docs/troubleshoot/app-framework/app-mustgather.md
Labels: area: webui, status: review

#1750 Document requirements for OMVS service in ZSS
  docs/user-guide/systemrequirements-zos.md
Labels: status: review

#1748 minor ha update
  docs/getting-started/overview.md
  docs/user-guide/configure-instance-directory.md
  docs/user-guide/configure-zowe-ha-server.md
  docs/user-guide/stop-zowe-zos.md
Labels: status: review

#1743 API mediation security - Tech Info language refactor
  docs/extend/extend-apiml/api-mediation-security.md
Labels: status: review

#1749 Update contributing.md
  docs/contribute/contributing.md
Labels: status: review

#1746 Add docs for troubleshooting launcher
  docs/troubleshoot/launcher/launcher-error-codes.md
  docs/troubleshoot/launcher/launcher-troubleshoot.md
  docs/troubleshoot/troubleshooting.md
  docs/user-guide/configure-instance-directory.md
  sidebars.js
Labels: status: review

#1772 Wizard documentation draft.
  docs/extend/extend-apiml/onboard-wizard.md
  docs/images/api-mediation/wizard-categories.png
  docs/images/api-mediation/wizard-enablers.png
  docs/images/api-mediation/wizard-onboard-button.png
  docs/images/api-mediation/wizard-save-button.png
  docs/images/api-mediation/wizard-validation.png
Labels: status: in-progress
