Repository zowe/docs-site, pull requests merged in 2021-09, with the labels that each got.

#1808 Fix link to custom metadata page
  docs/extend/extend-apiml/onboard-plain-java-enabler.md
  sidebars.js
Labels: type: bug, area: apiml

#1795 User Guide refactor
  .DS_Store
  docs/extend/extend-ze/ze-extensions.md
  docs/user-guide/install-overview.md
  docs/user-guide/install-zos.md
  docs/user-guide/installandconfig.md
  docusaurus.config.js
  sidebars.js
Labels: type: enhancement, area: zos-install-upgrade

#1821 Removed "technical preview" for HA docs
  docs/getting-started/zowe-architecture.md
  docs/user-guide/configure-instance-directory.md
  docs/user-guide/configure-sysplex.md
  docs/user-guide/install-ha-sysplex.md
  docs/user-guide/install-zos.md
Labels: High Availability

#1833 Fix TOC / typos / minor language corrections
  docs/user-guide/api-mediation/api-mediation-internal-configuration.md
Labels: status: review, area: apiml

#1831 Enhance Gateway CORS handling documentation
  docs/extend/extend-apiml/custom-metadata.md
  docs/user-guide/api-mediation/api-gateway-configuration.md
Labels: status: review, area: apiml

#1829 FIX: Install and use roadmaps table
  docs/getting-started/zowe-getting-started.md
Labels: status: review

#1845 Fixed bug 1809
  docs/user-guide/install-ha-sysplex.md
Labels: status: review

#1852 Resolved merge conflicts for 1788
  docs/extend/extend-desktop/mvd-authentication-api.md
  docs/extend/extend-desktop/mvd-logutility.md
Labels: type: bug, area: webui

#1766 Add section on defining AT-TLS configuration for client systems
  docs/user-guide/mvd-configuration.md
Labels: type: enhancement, area: webui
