Repository zowe/docs-site, pull requests merged in 2021-03, with the labels that each got.

#1590 docs: Added some minor improvements
  README.md
  docs/.github/pull_request_template.md
  docs/appendix/bill-of-materials.md
  docs/contribute/contributing.md
  docs/extend/extend-api/existingAPI.md
  docs/extend/extend-api/existingApp.md
  docs/extend/extend-apiml/api-mediation-components-of-URL.md
  docs/extend/extend-apiml/api-mediation-security.md
  docs/extend/extend-apiml/onboard-direct-eureka-call.md
  docs/extend/extend-apiml/onboard-overview.md
  docs/extend/extend-apiml/onboard-plain-java-enabler.md
  docs/extend/extend-apiml/onboard-static-definition.md
  docs/extend/extend-cli/cli-developing-a-plugin.md
  docs/extend/extend-cli/cli-setting-up.md
  docs/extend/extend-desktop/mvd-authentication-api.md
  docs/extend/extend-desktop/mvd-buildingplugins.md
  docs/extend/extend-desktop/mvd-conda.md
  docs/extend/extend-desktop/mvd-embeddingplugins.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/extend/extend-desktop/mvd-zluxappserver.md
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
  docs/getting-started/zowe-architecture.md
  docs/troubleshoot/cli/mustgather-cli.md
  docs/user-guide/api-mediation/api-gateway-configuration.md
  docs/user-guide/api-mediation/api-mediation-internal-configuration.md
  docs/user-guide/api-mediation/api-mediation-overview.md
  docs/user-guide/cli-installplugins.md
  docs/user-guide/cli-mqplugin.md
  docs/user-guide/cli-uninstall.md
  docs/user-guide/cli-updatingcli.md
  docs/user-guide/cli-usingcli.md
  docs/user-guide/configuring-docker.md
  docs/user-guide/mvd-configuration.md
  docs/user-guide/sdks-using.md
  docs/user-guide/ze-extensions.md
  docs/user-guide/ze-usage.md
  docs/user-guide/zowe-getting-started-tutorial.md
  docs/user-guide/zowe-zos-uninstall.md
Labels: status: review

#1581 Update the Zowe Explorer section
  docs/images/ze/ZE-allocate.gif
  docs/images/ze/ZE-associate.gif
  docs/images/ze/ZE-copy-member.gif
  docs/images/ze/ZE-delete-ds.gif
  docs/images/ze/ZE-edit-upload.gif
  docs/images/ze/ZE-member-filter-search.gif
  docs/images/ze/ZE-prof-update.gif
  docs/images/ze/ZE-set-params.gif
  docs/user-guide/ze-profiles.md
  docs/user-guide/ze-usage.md
Labels: area: zowe-explorer, status: review

#1589 Environment variable usage
  docs/user-guide/api-mediation/api-mediation-internal-configuration.md
Labels: area: apiml

#1551 Document the use of DSNL004I message for working out Db2 profile information
  docs/developer-guide/dev-building-zowe.md
  docs/developer-guide/dev-pipeline-zowe.md
  docs/user-guide/cli-db2plugin.md
Labels: status: review
