Repository zowe/docs-site, pull requests merged in 2021-05, with the labels that each got.

#1666 Doc update - TSO Command
  docs/images/ze/ZE-TSO-Command.gif
  docs/user-guide/ze-usage.md
Labels: area: zowe-explorer

#1668 Changes for enabling SSO
  docs/user-guide/configure-certificates-keystore.md
  package-lock.json
Labels: approved, area: zos-install-upgrade

#1674 Add documentation for the Zowe component upgrade script
  docs/extend/install-configure-zos-extensions.md
Labels: status: review

#1683 Fix SMP/E doc to add Zowe releases
  docs/user-guide/install-zowe-smpe.md
Labels: area: smp/e, status: review
