Repository zowe/docs-site, pull requests merged in 2021-06, with the labels that each got.

#1679 Documentation addition for extension installation and verification works
  docs/extend/install-configure-zos-extensions.md
  docs/getting-started/summaryofchanges.md
Labels: approved

#1681 zOSMF and Zowe requirements for HA in Sysplex
  docs/.vuepress/pages.json
  docs/getting-started/cli-getting-started.md
  docs/getting-started/overview.md
  docs/images/zosmf/zOSMF-HA.png
  docs/user-guide/systemrequirements-zosmf-ha.md
  docs/user-guide/systemrequirements.md
Labels: approved

#1631 Added word about how to get the sources image
  docs/user-guide/install-docker-image.md
Labels: status: review

#1715 Update ZE RNs
  docs/getting-started/summaryofchanges.md
Labels: area: zowe-explorer

#1688 WIP: Zowe HA documentation changes
  docs/.vuepress/pages.json
  docs/extend/lifecycling-with-zwesvstc.md
  docs/getting-started/diagrams/apiml-architecture
  docs/getting-started/diagrams/apiml-architecture.png
  docs/getting-started/overview.md
  docs/getting-started/summaryofchanges.md
  docs/images/common/zowe-ha-install-roadmap.png
  docs/images/common/zowe-ha-install-roadmap.pptx
  docs/images/common/zowe-zos-install-diagram.pptx
  docs/images/zowe-zos-install-diagram.png
  docs/user-guide/configure-caching-service-ha.md
  docs/user-guide/configure-instance-directory.md
  docs/user-guide/configure-sysplex.md
  docs/user-guide/configure-zos-system.md
  docs/user-guide/configure-zowe-ha-server.md
  docs/user-guide/configure-zowe-server.md
  docs/user-guide/configuring-docker.md
  docs/user-guide/install-ha-sysplex.md
  docs/user-guide/install-zos.md
  docs/user-guide/installandconfig.md
  docs/user-guide/scripted-configure-server.md
  docs/user-guide/stop-zowe-zos.md
  docs/user-guide/systemrequirements-zos.md
  docs/user-guide/systemrequirements-zosmf-ha.md
  docs/user-guide/systemrequirements.md
  docs/user-guide/upgrade-zos-system.md
  docs/user-guide/zowe-zos-uninstall.md
Labels: HA, docs, wip: do not merge

#1698 Updated links to CLI command help
  docs/appendix/zowe-cli-commannd-reference.md
  docs/getting-started/user-roadmap-zowe-cli.md
  docs/user-guide/cli-cicsplugin.md
  docs/user-guide/cli-db2plugin.md
  docs/user-guide/cli-ftpplugin.md
  docs/user-guide/cli-imsplugin.md
  docs/user-guide/cli-mqplugin.md
  docs/user-guide/cli-scsplugin.md
  docs/user-guide/cli-usingcli.md
Labels: area: cli, status: review, type: bug

#1506 Add Caching service and storage documentation
  docs/extend/extend-apiml/api-mediation-caching-service.md
  docs/extend/extend-apiml/api-mediation-redis.md
  docs/extend/extend-apiml/api-mediation-vsam.md
  docs/getting-started/zowe-architecture.md
  docs/images/api-mediation/caching-service.png
  docs/troubleshoot/troubleshoot-apiml-error-codes.md
  docs/user-guide/api-mediation/api-mediation-overview.md
  docs/user-guide/configure-instance-directory.md
Labels: docs

#1718 x509 authentication preference
  docs/extend/extend-apiml/api-mediation-security.md
Labels: x509
