Repository zowe/docs-site, pull requests merged in 2022-04, with the labels that each got.

#2106 Update apiml documentation for v2
  docs/extend/extend-apiml/api-mediation-caching-service.md
  docs/extend/extend-apiml/implement-new-saf-provider.md
  docs/troubleshoot/troubleshoot-apiml-error-codes.md
  docs/troubleshoot/troubleshoot-apiml.md
  docs/user-guide/api-mediation/api-gateway-configuration.md
  docs/user-guide/api-mediation/api-mediation-internal-configuration.md
Labels: area: apiml, v2

#2100 Cross Memory Server Chapter updates
  docs/user-guide/configure-xmem-server.md
  docs/user-guide/initialize-zos-system.md
Labels: v2

#2108 Server schema explanation
  docs/appendix/server-component-manifest.md
  docs/extend/packaging-zos-extensions.md
  docs/extend/server-schemas.md
Labels: area: webui, v2

#2111 updated daemon mode EV's per #1365
  docs/user-guide/cli-configuringcli-ev.md
Labels: area: cli, v2

#2095 Add Wizard YAML prefill docs (v2)
  docs/extend/extend-apiml/onboard-wizard.md
  docs/images/api-mediation/wizard-yaml-prefill.png
Labels: area: apiml, v2

#2028 ZSS error messages
  docs/troubleshoot/app-framework/zss-error-codes.md
  sidebars.js
Labels: area: webui, v2

#2063 [Needs Review] - Changes to App server Advanced configuration for V2
  docs/extend/extend-desktop/mvd-logutility.md
  docs/user-guide/mvd-configuration.md
Labels: area: webui, v2

#2113 Janan07/update safidt support
  docs/extend/extend-apiml/implement-new-saf-provider.md
  docs/extend/extend-apiml/onboard-plain-java-enabler.md
  docs/extend/extend-apiml/onboard-spring-boot-enabler.md
  docs/extend/extend-apiml/onboard-static-definition.md
Labels: area: apiml, v2

#2094 Update "extend" section of application framework for v2
  docs/extend/extend-desktop/mvd-adding-log-ids.md
  docs/extend/extend-desktop/mvd-apptoappcommunication.md
  docs/extend/extend-desktop/mvd-authentication-api.md
  docs/extend/extend-desktop/mvd-configdataservice.md
  docs/extend/extend-desktop/mvd-core-loggers.md
  docs/extend/extend-desktop/mvd-dataservices.md
  docs/extend/extend-desktop/mvd-desktopandwindowmgt.md
  docs/extend/extend-desktop/mvd-externals.md
  docs/extend/extend-desktop/mvd-iframecomm.md
  docs/extend/extend-desktop/mvd-installplugins.md
  docs/extend/extend-desktop/mvd-internationalization.md
  docs/extend/extend-desktop/mvd-logutility.md
  docs/extend/extend-desktop/mvd-plugindefandstruct.md
  docs/extend/extend-desktop/mvd-server-config.md
  docs/extend/extend-desktop/mvd-zluxdevenv.md
  docs/extend/extend-desktop/react-sample.md
Labels: area: webui, v2

#1916 [v2]updated app-server and zss variable names with valid prefixes
  docs/troubleshoot/app-framework/app-mustgather.md
  docs/troubleshoot/app-framework/app-troubleshoot.md
  docs/user-guide/configure-instance-directory.md
  docs/user-guide/verify-zowe-runtime-install.md
Labels: type: enhancement, area: webui, v2

#2114 added info about converting v1 to v2 profiles. added headings. reor…
  docs/user-guide/cli-using-using-profiles.md
Labels: area: zowe-explorer, v2

#2135 Update sidebars.js for apiml
  sidebars.js
Labels: area: apiml, v2

#2136 Work flows upd
  docs/images/configure/workflow-four.png
  docs/images/configure/workflow-one.png
  docs/images/configure/workflow-parameters.png
  docs/images/configure/workflow-threeB.png
  docs/images/configure/workflow-two.png
  docs/user-guide/certificates-setup.md
  docs/user-guide/configure-zowe-zosmf-workflow.md
  docs/user-guide/install-zowe-pswi-deployment.md
  sidebars.js
Labels: area: zos-install-upgrade, v2

#2115 per issue #2112
  docs/user-guide/ze-profiles.md
Labels: area: zowe-explorer, v2

#2140 Reorganize the topics about z/OS Install
  docs/extend/install-configure-zos-extensions.md
  docs/extend/k8s-conformance.md
  docs/extend/k8s-extend.md
  docs/troubleshoot/verify-fingerprint.md
  docs/user-guide/apf-authorize-load-library.md
  docs/user-guide/configure-instance-directory.md
  docs/user-guide/configure-xmem-server.md
  docs/user-guide/configure-zos-system.md
  docs/user-guide/grant-user-permission-zosmf.md
  docs/user-guide/initialize-mvs-datasets.md
  docs/user-guide/initialize-security-configuration.md
  docs/user-guide/initialize-vsam-dataset.md
  docs/user-guide/initialize-zos-system.md
  docs/user-guide/install-stc-members.md
  docs/user-guide/install-zos.md
  docs/user-guide/install-zowe-zos-convenience-build.md
  docs/user-guide/installandconfig.md
  docs/user-guide/k8s-config.md
  docs/user-guide/start-zowe-zos.md
  docs/user-guide/stop-zowe-zos.md
  docs/user-guide/verify-zowe-runtime-install.md
  sidebars.js
Labels: area: zos-install-upgrade, v2

#2145 updated time estimates, corrected syntax for plug-ins install
  docs/user-guide/cli-install-cli-checklist.md
  docs/user-guide/cli-installcli.md
Labels: area: cli, v2

#2104 update zowe Desktop docs
  docs/user-guide/mvd-using.md
Labels: area: webui, v2

#2152 server.json --> zowe.yaml
  docs/extend/extend-desktop/mvd-auth-plugins.md
  docs/extend/extend-desktop/mvd-server-config.md
  docs/user-guide/mvd-configuration.md
Labels: area: webui, v2

#2155 (fix; title) Set up Zowe cert with workflows
  docs/user-guide/certificates-setup.md
Labels: area: zos-install-upgrade, v2

#2150 cli/imperative rel notes v2
  docs/getting-started/release-notes/v2_0.md
Labels: area: cli, v2

#2161 add discovery service config to sidebars.js
  sidebars.js
Labels: docs, v2

#2144 added auto-init info for connecting to API-ML; fixed broken link in t…
  docs/getting-started/user-roadmap-zowe-cli.md
  docs/user-guide/cli-using-initializing-team-configuration.md
Labels: area: cli, v2

#2138 Update FAQ
  docs/getting-started/zowe_v2_faq.md
Labels: area: webui, v2
