Repository zowe/docs-site, pull requests merged in 2022-10, with the labels that each got.

#2409 staying on prev ZE version
  docs/images/ze/ZE-zowe-explorer-result-item.jpg
  docs/user-guide/ze-usage.md
Labels: area: zowe-explorer

#2371 change parm name
  docs/user-guide/api-mediation-standalone.md
Labels: area: apiml

#2416 Revert "change parm name"
  docs/user-guide/api-mediation-standalone.md
Labels: area: apiml

#2417 fix formatting basePackage
  docs/appendix/server-component-manifest.md
Labels: area: apiml

#2418 Zowe v2.4 release notes
  docs/getting-started/release-notes/v2_4_0.md
Labels: area: cli

#2407 Fix incorrect URL
  docs/user-guide/mvd-using.md
Labels: area: webui

#2430 added supported environs, reorganized FTP ext doc
  docs/images/ze/ZE-ftp-find-source.gif
  docs/images/ze/ZE-submit-jcl.gif
  docs/user-guide/ze-ftp-install-ze-ftp-ext.md
  docs/user-guide/ze-ftp-provide-feedback-contribute.md
  docs/user-guide/ze-ftp-supported-functions.md
  docs/user-guide/ze-ftp-using-ze-ftp-ext.md
  docs/user-guide/ze-provide-feedback-contribute.md
  docs/user-guide/ze-usage.md
  docs/user-guide/ze-use-cases.md
  sidebars.js
Labels: area: zowe-explorer
