Repository zowe/docs-site, pull requests merged in 2023-04, with the labels that each got.

#2774 Anax v270 suppotenvs cli
  docs/user-guide/cli-using-usingcli.md
  docs/user-guide/ze-usage.md
Labels: area: cli

#2830 editing v2.8 release notes
  docs/getting-started/release-notes/v2_8_0.md
Labels: docs

#2810 doc for how to change log and temp paths
  docs/images/troubleshoot/ZE/new-logs-folder-path.png
  docs/images/troubleshoot/ZE/new-temp-folder-path.PNG
  docs/images/troubleshoot/ZE/new-temp-folder-path.png
  docs/images/troubleshoot/ZE/write-access-error-logs-folder.png
  docs/images/troubleshoot/ZE/write-access-error-temp-folder.png
  docs/troubleshoot/ze/troubleshoot-ze.md
Labels: area: zowe-explorer

#2805 updating APIML integration content
  docs/user-guide/cli-using-integrating-apiml.md
  docs/user-guide/cli-using-using-team-profiles.md
Labels: area: cli

#2837 updating Use Cases w/ polling spool files content
  docs/images/ze/ZE-start-polling-V2.gif
  docs/user-guide/ze-use-cases.md
Labels: area: zowe-explorer

#2842 Update the parameters in zowe.yaml file
  docs/appendix/zwe_server_command_reference/zwe/zwe-start.md
  docs/user-guide/api-mediation/api-mediation-smf.md
  docs/user-guide/configure-xmem-server.md
  docs/user-guide/install-zos.md
  docs/user-guide/systemrequirements-zos.md
Labels: type: bug

#2845 Anax v2.8 addingspoolpollcontent ze
  docs/images/ze/ZE-start-polling-V2.gif
  docs/user-guide/ze-use-cases.md
Labels: area: zowe-explorer

#2850 documenting workaround for IBM Db2 known issue
  docs/troubleshoot/cli/troubleshoot-cli-plugins.md
  docs/user-guide/cli-swreqplugins.md
Labels: area: cli, type: troubleshoot

#2851 adding missing info in cong team profile steps
  docs/user-guide/ze-profiles.md
Labels: area: cli
