Repository zowe/docs-site, pull requests merged in 2023-10, with the labels that each got.

#3129 documenting how to associate languages, file extensions
  docs/getting-started/zowe_faq.md
  docs/user-guide/ze-usage.md
Labels: area: zowe-explorer

#3128 Add Release Notes for API ML bug fixes for v1.28.5
  versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md
Labels: area: apiml

#3122 Address broken link in Issue 3110
  docs/getting-started/zowe-security-authentication.md
Labels: area: apiml

#3132 Add API ML release notes for 1.28.5
  versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md
Labels: area: apiml

#3136 Add apiml bug fixes for previous 1.28.x versions
  versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_3.md
  versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_4.md
Labels: area: apiml

#3142 refactor drop down menu and some top-level article titles
  docs/contribute/roadmap-contribute.md
  docs/troubleshoot/troubleshooting.md
  docs/user-guide/install-overview.md
  docs/user-guide/zowe-getting-started-tutorial.md
  docusaurus.config.js
Labels: docs

#3143 Update sidebars.js with Personal Access Token doc
  sidebars.js
Labels: area: apiml

#3147 Fix links in API ML and certificate doc
  docs/user-guide/api-mediation/upgrade-zowe-no-downtime.md
  docs/user-guide/generate-certificates.md
Labels: area: apiml

#3137 documenting auth mechanisms
  docs/extend/extend-cli/cli-devTutorials.md
  docs/troubleshoot/cli/troubleshoot-cli-credentials.md
  package-lock.json
  package.json
  sidebars.js
Labels: area: cli

#3138 adding note re: non-ASCII characters and FTP
  docs/user-guide/cli-ftpplugin.md
  docs/user-guide/ze-ftp-using-ze-ftp-ext.md
Labels: area: cli, area: zowe-explorer

#3151 Anax v1.28.5 releasenotes cli
  tpsr/tpsr-v1.28.5.md
  versioned_docs/version-v1.28.x/getting-started/release-notes/v1_28_5.md
Labels: area: cli, area: zowe-explorer

#3168 fixing some broken links
  docs/user-guide/api-mediation/upgrade-zowe-no-downtime.md
  docs/user-guide/import-certificates.md
  docs/user-guide/k8s-introduction.md
  versioned_docs/version-v2.10.x/user-guide/import-certificates.md
Labels: docs

#3172 Fix for broken API ML link in v2.9 for Issue 3171
  versioned_docs/version-v2.9.x/troubleshoot/troubleshoot-apiml.md
Labels: area: apiml

#3179 bumping new release version, adding placeholder files
  docs/getting-started/release-notes/v2_12_0.md
  docusaurus.config.js
  sidebars.js
  tpsr/tpsr-v2.12.x.md
Labels: docs

#3182 adding Zowe CLI release notes
  docs/getting-started/release-notes/v2_12_0.md
Labels: area: cli

#3187 API ML features and bugfixes for v2.12
  docs/getting-started/release-notes/v2_12_0.md
Labels: area: apiml

#3175 Anax v2.12 sortfilter ze
  docs/images/ze/ZE-filtering-a-specific-PDS.gif
  docs/images/ze/ZE-filtering-profile-PDS-members.gif
  docs/images/ze/ZE-sorting-a-specific-PDS.gif
  docs/images/ze/ZE-sorting-jobs.gif
  docs/images/ze/ZE-sorting-profile-PDS-members.gif
  docs/user-guide/ze-use-cases.md
  docs/user-guide/ze-working-with-data-sets.md
  docs/user-guide/ze-working-with-jobs.md
  docs/user-guide/ze-working-with-uss-files.md
  sidebars.js
Labels: area: zowe-explorer

#3192 adding a link; removing ZE headers
  docs/getting-started/release-notes/v2_12_0.md
Labels: area: cli

#3149 Update zowe-security-authentication.md
  docs/getting-started/zowe-security-authentication.md
Labels: type: bug

#3188 documenting new Manage Profile func in ZE
  docs/user-guide/ze-profiles.md
Labels: area: zowe-explorer

#3198 Zowe v2.12 TPSRs
  tpsr/tpsr-v2.12.x.md
Labels: docs

#3199 removed headers for missing release notes
  docs/getting-started/release-notes/v2_12_0.md
Labels: docs

#3206 Add content back to ze chunked articles from ze-use-cases
  docs/user-guide/ze-working-with-data-sets.md
  docs/user-guide/ze-working-with-jobs.md
  docs/user-guide/ze-working-with-uss-files.md
Labels: area: zowe-explorer

#3058 install and config redesign working branch
  .DS_Store
  docs/appendix/zowe-security-glossary.md
  docs/getting-started/zowe-security-overview.md
  docs/images/install/4-installation-methods.png
  docs/images/install/Convenience-build-install.png
  docs/images/install/PSWI-install.png
  docs/images/install/SMPE-install.png
  docs/images/install/container-install-1.png
  docs/images/install/container-install-2.png
  docs/images/install/container-install-34.png
  docs/images/install/container-install-5.png
  docs/images/install/container-install-6.png
  docs/images/install/containerization-install.png
  docs/user-guide/address-authentication-requirements.md
  docs/user-guide/address-browser-requirements.md
  docs/user-guide/address-network-requirements.md
  docs/user-guide/address-security-requirements.md
  docs/user-guide/address-storage-requirements.md
  docs/user-guide/configure-uss.md
  docs/user-guide/configure-zos-system.md
  docs/user-guide/initialize-security-configuration.md
  docs/user-guide/install-nodejs-zos.md
  docs/user-guide/install-zos.md
  docs/user-guide/install-zowe-pswi-acquire.md
  docs/user-guide/install-zowe-pswi-address-requirements.md
  docs/user-guide/install-zowe-pswi-deployment.md
  docs/user-guide/install-zowe-pswi.md
  docs/user-guide/install-zowe-smpe-overview.md
  docs/user-guide/install-zowe-smpe-zosmf-workflow.md
  docs/user-guide/install-zowe-smpe.md
  docs/user-guide/install-zowe-zos-convenience-build.md
  docs/user-guide/installandconfig.md
  docs/user-guide/k8s-config.md
  docs/user-guide/k8s-downloading.md
  docs/user-guide/k8s-introduction.md
  docs/user-guide/k8s-prereqs.md
  docs/user-guide/k8s-using.md
  docs/user-guide/systemrequirements-zos.md
  docs/user-guide/systemrequirements-zosmf-lite.md
  docs/user-guide/systemrequirements-zosmf.md
  docs/user-guide/zos-components-installation-checklist.md
  docs/user-guide/zosmf-install.md
  sidebars.js
Labels: area: install and config

#3215 non-doc-squad test
  .github/workflows/pull-request-checker.yml
Labels: area: cli, 1.0.0, area: install and config
